# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddEdit(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(631, 431)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 20, 111, 21))
        self.label.setObjectName("label")
        self.name = QtWidgets.QLineEdit(Form)
        self.name.setGeometry(QtCore.QRect(160, 20, 461, 20))
        self.name.setObjectName("name")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 131, 21))
        self.label_2.setObjectName("label_2")
        self.percent = QtWidgets.QLineEdit(Form)
        self.percent.setGeometry(QtCore.QRect(160, 70, 461, 20))
        self.percent.setObjectName("percent")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(20, 120, 131, 21))
        self.label_3.setObjectName("label_3")
        self.type = QtWidgets.QLineEdit(Form)
        self.type.setGeometry(QtCore.QRect(160, 120, 461, 20))
        self.type.setObjectName("type")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(20, 170, 131, 21))
        self.label_4.setObjectName("label_4")
        self.desc = QtWidgets.QLineEdit(Form)
        self.desc.setGeometry(QtCore.QRect(160, 170, 461, 20))
        self.desc.setObjectName("desc")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(20, 220, 131, 21))
        self.label_5.setObjectName("label_5")
        self.price = QtWidgets.QLineEdit(Form)
        self.price.setGeometry(QtCore.QRect(160, 220, 461, 20))
        self.price.setObjectName("price")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(20, 270, 131, 21))
        self.label_6.setObjectName("label_6")
        self.volume = QtWidgets.QLineEdit(Form)
        self.volume.setGeometry(QtCore.QRect(160, 270, 461, 20))
        self.volume.setObjectName("volume")
        self.save = QtWidgets.QPushButton(Form)
        self.save.setGeometry(QtCore.QRect(430, 300, 191, 25))
        self.save.setText("")
        self.save.setObjectName("save")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Сорт"))
        self.label_2.setText(_translate("Form", "Степень обжарки(%)"))
        self.label_3.setText(_translate("Form", "Вид"))
        self.label_4.setText(_translate("Form", "Описание"))
        self.label_5.setText(_translate("Form", "Цена(руб.)"))
        self.label_6.setText(_translate("Form", "Объём(л)"))
